server:
  port: 8080

spring:
  application:
    name: boot-user-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://wxp520.top:3306/boot?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.xp.shop.pojo